### PR TITLE
Feature/add new xslts

### PR DESCRIPTION
**Pull request by CAMOBAP**
- https://github.com/metanorma/mn-native-pdf/issues/230

### CODE REVIEW

**Review by opoudjis — CHANGES_REQUESTED** [review]
OK, thank you. OTOH, Ruby 3.0 is now breaking from an import in fontist?

**Comment by ronaldtse** [comment]
> OK, thank you. OTOH, Ruby 3.0 is now breaking from an import in fontist?

Posted here: https://github.com/fontist/fontist/issues/220

**Comment by CAMOBAP** [comment]
Also here is a strange fail for all windows runs, I thought that we use VCR exactly to avoid such problem...

**Comment by alexeymorozov** [comment]
Released `fontist` with support of Ruby 3.0 in v1.8.7.

Please note that this repo needs to update `rake` to v13 in order to build native extensions with Ruby 3.0.

**Pull request merged**
