### PR TITLE
finalize arabic version

### PR DESCRIPTION
**Pull request by AhMohsen46**
just a single edit, the rest left as is since they're abbreviations, that has no mappings in arabic as far as i Know
I can still do the mapping with words' initials if we want

### CODE REVIEW

**Comment by AhMohsen46** [comment]
something wrong with gem file in failing tests
```
    In Gemfile:
      Ruby
  
      metanorma-itu was resolved to 1.3.5, which depends on
        Ruby (>= 2.5.0)
  
  Ruby (>= 2.5.0), which is required by gem 'metanorma-itu', is not available in
  the local ruby installation
  Took  15.68 seconds
```

**Comment by ronaldtse** [comment]
Thanks @AhMohsen46 !

**Comment by ronaldtse** [comment]
Rebased and tests passing.

**Comment by AhMohsen46** [comment]
awesome, thanks @ronaldtse !

**Pull request merged**
